### ISSUE TITLE
Add Cirrus CI

### ISSUE THREAD

**Issue by asomers** [domodwyer/pmc-rs#5]
It wasn't around when you began this project, but nowadays Cirrus CI is the best way to do CI with Github on FreeBSD.  If you enable it, I can write a PR configuring it for you.  Just follow the guide at https://cirrus-ci.org/guide/quick-start/ but stop at "Post Installation".

**Comment by domodwyer** [comment]
Hi @asomers ,

I'd love a PR! I shall enable it now 👍 

Thanks for all your contributions - much appreciated!

Dom

**Comment by domodwyer** [comment]
Done! I have desperately needed a CI platform for all the PMC bits - thank you for pointing Cirrus CI out!
