### ISSUE TITLE
Consider merging pmc-rs and pmc-sys into a workspace

### ISSUE THREAD

**Issue by asomers** [domodwyer/pmc-rs#6]
I find that tightly coupled pairs of crates like pmc-rs and pmc-sys are easiest to develop when they're in a workspace in a single repository.  I suggest you merge pmc-sys and pmc-rs into the same repo.  For an example, see https://github.com/asomers/blosc-rs .

**Comment by domodwyer** [comment]
Yes you're right, I completely agree it would be way easier.

 I was just starting out with rust when I wrote pmc-rs, but now I'm older and wiser and will move it across.
