### ISSUE TITLE
Build fails on FreeBSD 12.0 and newer

### ISSUE THREAD

**Issue by asomers** [domodwyer/pmc-rs#7]
In FreeBSD 12.0, the `pmc_allocate` function got a new argument.  pmc-rs needs to be updated accordingly.

```
$ cargo check
...
rror[E0061]: this function takes 6 arguments but 5 arguments were supplied
   --> src/counter.rs:173:15
    |
173 |         if unsafe { pmc_allocate(spec.as_ptr(), c.pmc_mode, 0 as u32, cpu, &mut id) } != 0 {
    |                     ^^^^^^^^^^^^ -------------  ----------  --------  ---  ------- supplied 5 arguments
    |                     |
    |                     expected 6 arguments
```

https://svnweb.freebsd.org/base?view=revision&revision=334701

**Comment by domodwyer** [comment]
Ah that is unfortunate! I guess it is time to update to 12...

Thanks for letting me know!

**Comment by domodwyer** [comment]
I had a go at this (including a _much needed_ API redesign - see [this diff](https://github.com/domodwyer/pmc-rs/compare/feat/freebsd-12?expand=1)) but I hit a roadblock: it seems `libpmc` now uses C++ somewhere in the stack, and after explicitly linking to `libc++`, I still get the following error at runtime when running tests:

```
     Running target/debug/deps/pmc-a0be449f3957c7e2
ld-elf.so.1: /usr/lib/libpmc.so.5: Undefined symbol "__gxx_personality_v0"
error: test failed, to rerun pass '--test pmc'
```

This seems to be a problem that should be solved in `pmc-sys` - the changes I made to get this far are here: https://github.com/domodwyer/pmc-sys/commit/2d972ea053c50d40f68dacaad4834fc3f1382e5c

I'm not very familiar with C++ and didn't have much luck googling, so unfortunately shelving this for now.

**Comment by asomers** [comment]
Crap.  I think the problem is https://svnweb.freebsd.org/base/head/usr.sbin/pmcstat/Makefile?revision=334749&view=markup .  That revision changed libpmc from using a C ABI to a C++ ABI, even though it probably didn't need to.  And according to https://doc.rust-lang.org/nomicon/ffi.html, that's a non-starter for Rust.  I'll try to get it changed back in time for FreeBSD 13.0; there just might be sufficient time to do it.

**Comment by domodwyer** [comment]
Yeah my understanding is that C++ with Rust is _tricky_ to say the least. I'm not familiar with it enough to know if there's a possible workaround in this situation - any help would be awesome - I'd love to get an update out and perhaps start building some tooling around it!

**Comment by asomers** [comment]
So it's not as bad as I though.  libpmc's ABI is still C.  It just needs libc++ linked in.  I don't know why Cargo isn't linking to it.  AFAIK, all that should be needed is:
```rust
println!("cargo:rustc-link-lib=pmc");
println!("cargo:rustc-link-lib=c++");
```
which you have.  I'll go head and fix libpmc in FreeBSD 13.0 , but you'll have to keep working on pmc-sys.

**Comment by asomers** [comment]
I fixed the linking issue upstream, and it will be included in 13.0 and 12.3.  I still don't know why Cargo seems to be ignoring `cargo:rustc-link-lib=c++"`, however.

**Comment by asomers** [comment]
So I finally found the correct solution.  Rust "helpfully" removes linked libraries if it thinks they aren't needed.  That caused it to remove libc++, which was depended upon transitively by libpmc.  The solution is to force it to link by using the obscure `-as-needed` option.  Something like this ought to work:
```rust
println!("cargo:rustc-link-lib=dylib:-as-needed=c++");
```
You may want to add that in, if you still build this library for FreeBSD 12.

**Comment by domodwyer** [comment]
Wow that is.... obscure... Where on earth did you discover this? I can't even find any docs, just the odd GitHub issue.

Amazing digging!

**Comment by asomers** [comment]
Actually, it was `rustc --help` that tipped me off.  It showed me what to google for.
